# Copyright 2024 HM Revenue & Customs
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

include "frontend.conf"

appName = "vat-return-period-frontend"
play.http.router = prod.Routes
play.i18n.langs  = ["en", "cy"]
play.i18n.langCookieHttpOnly = true

# Provides an implementation and configures all filters required by a Platform frontend microservice.
play.http.filters = "config.filters.ServiceFilters"

# Default http client
play.modules.enabled += "uk.gov.hmrc.play.bootstrap.HttpClientModule"
play.modules.enabled += "uk.gov.hmrc.play.bootstrap.HttpClientV2Module"

# Custom error handler
play.http.errorHandler = "config.ServiceErrorHandler"

play.filters.enabled += play.filters.csp.CSPFilter
play.filters.headers.xssProtection = "1"

# Play Modules
# ~~~~
# Additional play modules can be added here
play.modules.enabled += "uk.gov.hmrc.play.bootstrap.HttpClientModule"
play.modules.enabled += "uk.gov.hmrc.play.bootstrap.AuthModule"
play.modules.enabled += "config.Module"

features {
  stubAgentClientLookup.enabled = true
  showUserResearchBanner.enabled = true
}

microservice {
  metrics {
    graphite {
      enabled = true
    }
  }

  services {
    contact-frontend {
      host = localhost
      port = 9250
    }

    auth {
      host = localhost
      port = 8500
    }

    vat-subscription {
      host = localhost
      port = 9567
    }

    vat-subscription-dynamic-stub {
      host = localhost
      port = 9156
    }

    contact-preferences {
      host = localhost
      port = 9592
    }
  }
}

metrics {
  enabled = true
}

auditing {
  enabled = true
}

google-analytics {
  token = N/A
  host = auto
}

platform {
  host = "http://localhost:9167"
}

contact-frontend {
  host = "http://localhost:9250"
  serviceId = "VATC"
}

signIn {
  url = "http://localhost:9949/auth-login-stub/gg-sign-in"
  continueBaseUrl = "http://localhost:9150"
  continueUrl = "/vat-through-software/account/change-business-details"
}

government-gateway {
  host = "http://localhost:9553"
}

feedback-frontend {
  host = "http://localhost:9514"
  url = "/feedback"
}

manage-vat-subscription-frontend {
  host = "http://localhost:9150"
  url = "/vat-through-software/account/change-business-details"
}

vat-agent-client-lookup-frontend {
  host = "http://localhost:9149"
  homeUrl = "/vat-through-software/representative/client-vat-account"
  startUrl = "/vat-through-software/representative/client-vat-number"
  unauthorisedUrl = "/vat-through-software/representative/unauthorised-for-client"
}

vat-summary-frontend {
  host = "http://localhost:9152"
  detailsUrl = "/vat-through-software/vat-overview"
}

accessibility-statement.service-path = "/vat-through-software"

business-tax-account {
  host = "http://localhost:9020"
  homeUrl = "/business-account"
}

gov-uk {
  agentServices = "https://www.gov.uk/guidance/get-an-hmrc-agent-services-account"
  mtdVat = "https://www.gov.uk/guidance/making-tax-digital-for-vat"
}

tracking-consent-frontend {
  gtm.container = "d"
}

timeout {
  period: 900
  countDown: 120
}

urBanner {
    url = "https://www.gov.uk/government/organisations/hm-revenue-customs"
}

play-frontend-hmrc {
    forceServiceNavigation = true
}